### ISSUE TITLE
Bind and use the external WS.

### ISSUE THREAD

**Issue by JensThanx** [JensThanx/SCM-BPMN-Lab#3]
Import, bind the WSDL of external WS to own WS.
Call at least one of the external WS from own WS successfully.

**Comment by JensThanx** [comment]
Not able to call.
Using "invoke" just turns yellow, but never completes.
Testing with SOAPUI was succesful, got a reply and everything.

**Comment by wannerdev** [comment]
Was hast du bei der WSDL Host: port eingegeben einfach localhost:8080 oder ?

**Comment by JensThanx** [comment]
Meinst Du für den "InventoryCallbackService"?
http://46.101.159.46:3000/InventoryCallbackService/InventoryCallbackPort

oder für den eigenen Service?
http://localhost:8080/ode/processes/<Name des eigenen BPEL Prozesses>
bzw.
http://localhost:8080/ode/processes/<Name des eigenen BPEL Prozesses>Callback

**Comment by wannerdev** [comment]
Ja...
Naja also wenn ich ein Prozess erstelle und die damit verbundene WSDL angebe wird die WSDL mit Fehler bei Zeile 571 markiert. Dort sind nur Platzhalter drinn.

**Comment by manh3141** [comment]
So eintragen wie Jens das hat löst das Problem bei mir - oder den gesamten Block vorerst auskommentieren. Das wird nur für den asynchronen Aufruf benötigt, der kommt ja erst später.

**Comment by JensThanx** [comment]
Joa, das ist so. Aber eigentlich sollte das kein Problem beim Deploy
sein, wenn Du den Callback nicht aufrufen möchtest.
Ansonsten ist in den Folien noch eine Adresse genannt (für alle WS !!):
http://localhost:8080/SimpleWebService/services/SimpleService/

Am 15.11.2016 um 17:54 schrieb wannerdev:
