### ISSUE TITLE
Frontend Design

### ISSUE THREAD

**Issue by JensThanx** [JensThanx/SCM-BPMN-Lab#7]
Make a realistic draft for a frontend implementation.

**Comment by wannerdev** [comment]
da du angerufen hast hier mal mein momentanes php geschreibsel

falls es dich interessiert was ich grad mach
````
<!DOCTYPE HTML>
<html>
 <head>
   <meta charset="utf-8" />
   <title>BPM-WebUI-Group10</title>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
   <script type="text/javascript" src="script.js"></script>
   <script type="text/javascript" src="bootstrap-3.3.5-dist/js/bootstrap.min.js"></script>
   <link rel="stylesheet" type="text/css" href="bootstrap-3.3.5-dist/css/bootstrap.css"/>
<?php 

	class paymentDetails {
		
		function paymentDetails($varbankName, $varbankAddress, $varaccountNumber, $varaccountHolderName){
			$this->bankName = $varbankName;
			$this->bankAddress = $varbankAddress;
			$this->accountNumber = $varaccountNumber;
			$this->accountHolderName = $varaccountHolderName;
		}
	}
	
	class product{
		
		function product($_productId, $_numberOfItems){
			$this->productId = $_productId;
			$this->numberOfItems = $_numberOfItems;
		}
	}

	/*
	<tns:productId>44162d90-9315-4acc-980e-cf975c6b9397</tns:productId>
	<tns:numberOfItems>1</tns:numberOfItems>
	*/

//	$webSv = new SoapClient("C:\eclipse\eclipse_win64\workspace\ManhS\ConductOrderArtifacts.wsdl");

	$webSv = new SoapClient("http://46.101.159.46:32770/ode/processes/ConductOrder?wsdl");
 	$webSv2 = new SoapClient("C:\eclipse\eclipse_win64\workspace\sync\\rev0\FlowSOG.wsdl");
// 	$webAS = new SoapClient("C:\eclipse\eclipse_win64\workspace\\test\ConductOrderArtifacts.wsdl");
// 	$webAS2 = new SoapClient("C:\eclipse\eclipse_win64\workspace\\test\FlowSOG.wsdl");
	$list = $webSv->__getFunctions();
	var_dump($list);
	?>
	 </br>
	 </br>
	<?php
	$list = $webSv2->__getFunctions();
	var_dump($list);
	?>
	 </br>
	 </br>
	 <?php 
//	var_dump($webSv->checkAvailability(array('productId' => '479e8b20-3697-4609-9ed6-bde2a4b22e41')));
              
	?>
   <style>
		html{
			position: relative;
			min-height: 100%;
		}
	    #head {
	       background-color: #116;
	    }
		#footer {
			background-color: #EEF;
			position: absolute;
			left: 0;
			bottom: 0;
			height: 20px;
			width: 100%;
			overflow:hidden;
		}
		.container {
			padding-bottom: 20px;
		}
   </style>

 </head>

 <body>
   <nav class="navbar navbar-inverse">
      <div class="container-fluid" id="head">
         <div class="navbar-header">
            <a class="navbar-brand" href="#">
               BPM-WebUI-Group10
            </a>
         </div>
      </div>
   </nav>
   
   <div class="container">
      <div id="alertspace"></div>
	  <div class="col-sm-2 col-md-3"></div>
      
	  <div class="col-sm-8 col-md-6">
	  <?php 
	  //"479e8b20-3697-4609-9ed6-bde2a4b22e41",
	  
	  $ConductOrderparam = array(
		  	"customerID" => $_GET["cid"],
		  	"product" => new product($_GET['pid1'], $_GET['pno1']),
		  	"product" => new product($_GET['pid2'], $_GET['pno2']),  		 
		  	"shipingAddress" => $_GET["address"],
		  	"paymentDetails" => new paymentDetails($_GET["bn"], $_GET["bic"], $_GET["iban"], $_GET["ah"]),
		  	"shippingDate" => $_GET["sd"]
		  	
		  	);
		  	
	  var_dump($webSv->__call(conductOrder,$ConductOrderparam));	  	
	  ?>
            
	  <?php echo $_GET["cid"]; ?><br>
	  <?php echo $_GET["pid1"]; ?><br>
	  <?php echo $_GET["pno1"]; ?><br>
	  <?php echo $_GET["pid2"]; ?><br>
	  <?php echo $_GET["pno2"]; ?><br>
	  <?php echo $_GET["address"]; ?><br>
	  <?php echo $_GET["bn"]; ?><br>
	  <?php echo $_GET["bic"]; ?><br>
	  <?php echo $_GET["iban"]; ?><br>
	  <?php echo $_GET["ah"]; ?><br>
	  <?php echo $_GET["sd"]; ?><br>
       </div> 
	
	<div class="col-sm-2 col-md-3"></div>	   
    </div> 

    <div class="container-fluid" id="footer">
       (C) Manh Phi Nguyen, Johannes Wanner, Jens Thenent, 2016
    </div>

 </body>
</html>
```
`

**Comment by JensThanx** [comment]
Ja, cool :)
Wir sind also auf dem Weg.
Konntest Du den WS erreichen, irgendwo?


Am 04.12.2016 um 14:03 schrieb wannerdev:

**Comment by wannerdev** [comment]
Also den von der uni schon unseren eigenen nur beschränkt, aber den Service(Conductorder ) zum starten von will nicht. Bzw er sagt er will ein Array als parameter zum transformieren was ich ihm geb aber i-wie is der wohl nicht so wie der Service ihn will. was ich noch machen will ist bei wireshark schauen wie er momentan mein array in xml transformiert und das dann mit dem input xml abgleichen

**Comment by JensThanx** [comment]
Hat Wireshark was gebracht? Oder kannst Du sonst irgendwie schauen, was genau der SOAP-Client abschickt?

**Comment by JensThanx** [comment]
Ich habe nun die letzten Handgriffe bei der Shopseite gemacht und committed.
Weitere Schritte von mir:
* für Index2.php eine If-then Weiche anlegen und darin das UI hinterlegen für Erfolg/Misserfolg ("Danke für Ihre Bestellung" vs. "Unser Shop ist nicht verfügbar, versuchen Sie es später noch einmal"), dieses schicke ich dann @wannerdev damit er die Bedingung eintragen kann
* den finalen PHP Code von @wannerdev in die finale index2.php eintragen
* testen ;)

**Comment by wannerdev** [comment]
aaaalso ich hab über Wireshark das xml zeug jetzt nicht gefunden.
Ich hab aber einiges versucht und  kp vlt liegts an meiner php Version.
Ich hab auch mal die XML selber nachgebaut.
Falls du noch Elan hast kannst es ja mal bei dir ausprobieren...
Ich glaube ich hab den Namespace nicht richtig angegeben oder den Array nicht richtig angegeben, oder man muss den Content type noch definieren auf application/xml ...

**Comment by JensThanx** [comment]
Ok, ich schau morgen einfach mal drüber und vielleicht fällt mir was auf. Ich melde mich wenn ich ne Idee habe oder was nicht verstehe.

**Comment by JensThanx** [comment]
Wow. Ich bräuchte mal etwas Doku oder Erläuterung... das sieht alles eher nach einem Haufen Debug-Informationen aus als nach einer Lösung ;)

**Comment by JensThanx** [comment]
Läuft.

**Comment by manh3141** [comment]
Läuft?

**Comment by JensThanx** [comment]
Ich mach das UI noch bisschen hübsch. Ist nicht perfekt, aber ich lads auf jeden Fall heute abend noch hoch.

**Comment by manh3141** [comment]
Ah okay, ich dachte du meintest damit J's Code.

Call to actions sind jetzt nur noch Backend-Integration und BPMNs updaten. Ich bin grad auch an der Backend-Integration dran.

**Comment by JensThanx** [comment]
Ja, ich mein Backend.

**Comment by JensThanx** [comment]
Ok, das Problem sind die Timeouts bei Fehlern. 
Das erzeugt eine Exception die sich nicht fangen lässt. Der SoapClient "stirbt" und der weitere Code wird nicht ausgeführt. Es wird aber eine Fehlermeldung ausgegeben.

Im Erfolgsfall ist aber alles OK.

**Comment by JensThanx** [comment]
Habs hier auch mal abgelegt.

http://nekobukuro.net/BPM

Wichtig ist noch, dass der richtige Port zum WS angegeben ist. Darum hab ich das auch in die UI integriert.

**Comment by JensThanx** [comment]
Ok, ich mach zu. Das wars von mir dazu.
